spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/serverdb
    password: 2020@nde
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
server:
  port: 8089